### ISSUE TITLE
Costume passives bug

### ISSUE THREAD

**Issue by JordanLeich** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#10]
Author: [Cohollow](https://discord.com/channels/449510825385000960/449511007811796993/922498671042514964)

Date: 20.12.2021

Bug:
Most of the costume passives that add to a characters power damage don't work. (Eg. Storm, Human Torch) Thing's powers passive works.

**Comment by JordanLeich** [comment]
Here's a rundown of what I could find that looks wrong
-Mr. fantastic-
Original skin has wrong max health icon.
New marvel skin has wrong combo bonus xp icon, could just use the normal yellow arrow xp icon for this.
Classic skin has wrong reflect damage icon.

-Ms. Marvel-
Warbird skin has wrong energized fists icon (it should resemble more of an energy icon).

-Silver Surfer-
Classic skin has wrong cosmic mastery icon (it should be an XP icon).

-Storm-
Classic skin has wrong static charge icon (it should resemble more of an energy icon).
Retro skin has wrong combo bonus xp icon, could just use the normal yellow arrow xp icon for this.

-Iron Man-
War Machine skin has wrong boost resistances icon.

**Comment by ak2yny** [comment]
There may be other, non-power-boost passives, which may be wrong. Cohollow had a list (which may be lost), and other MUA fans reported generally buggy passives as well (no specifics known yet).

**Comment by JordanLeich** [comment]
I just tested Storm, Human Torch, and Thing's costume power damage passives and they all did not work as intended. They all output the same amount of damage with powers no matter how highly or low upgraded the power damage passive is. I will look into fixing this if possible.

**Comment by JordanLeich** [comment]
This for example is the code responsible for Storms passive to add dmg to all powers but it doesn't work as intended.

`talent {
   descname = Weather Mastery ;
   description = Increases the $DMG of all powers. ;
   icon = 7 ;
   icon_texture = textures/ui/storm_icons1.png ;
   name = storm_outfit22 ;
   skin = 1 ;
   type = passive ;
      talentvalues {
         talentvalue {
         level = 1 ;
         name = storm_outfit22_pct ;
         value = 1.03 ;
         }

         talentvalue {
         level = 9 ;
         name = storm_outfit22_pct ;
         value = 1.15 ;
         }

      }

      level {
      count = 9 ;
      description = %storm_outfit22_pct:s Power $DMG ;
         powerup {
         life = -1 ;
            affecter {
            attribute = atk_damage ;
            level = %storm_outfit22_pct ;
            scope_powers = true ;
            }

         }`

**Comment by techurious** [comment]
Are you sure it doesn't work? Try changing the value to 2 to see the obvious damage change that should doubly increase power damage. Low damage bonus (3 - 15%) is barely noticeable. If it doesn't work, then it needs "affect_type = scale" to function.

**Comment by JordanLeich** [comment]
> Are you sure it doesn't work? Try changing the value to 2 to see the obvious damage change that should doubly increase power damage. Low damage bonus (3 - 15%) is barely noticeable. If it doesn't work, then it needs "affect_type = scale" to function.
> 
> 
> 
> EDIT: just checked, and it does need affect_type = scale. Although it doesn't work for Chain Lightining damage for some reason. As if it's not a power (might have to do with indirect damage via harming powerup).

Yeah I was having major issues with adding affect_type = scale to storms talent file, it wouldn't compile, im not sure if this also applies to human torch or colossus because I haven't looked at them yet.

**Comment by techurious** [comment]
@JordanLeich what are you using for compiling? I added that with no problem using the QuickBatch. Don't forget about the syntax.

**Comment by JordanLeich** [comment]
> @JordanLeich what are you using for compiling? I added that with no problem using the QuickBatch. Don't forget about the syntax.
> 
> 

I was using the good old XMLBCUI program which is more than likely the issue, I was switch over to QuickBatch when I get the chance to.

**Comment by techurious** [comment]
P.S. are we still using the repository for updates? I could fix Storm's talent file myself in that case.

**Comment by JordanLeich** [comment]
> P.S. are we still using the repository for updates? I could fix Storm's talent file myself in that case.

I believe me and @ak2yny are so yeah you can go ahead and fix it if you'd like. I'm not home for awhile so I can't fix anything right now but I know that human torch and colossus likely suffer from the same problem as storm. I know that mr fantastics increase power damage passive already works.

**Comment by JordanLeich** [comment]
So it turns out that Storm from what I could find was the only character missing the affect_type = scale in the talent file so I just fixed that. However, I will leave this issue open on GitHub just in the case that we find more costume passive bugs or cohollow shares his list of bugs.

**Comment by ak2yny** [comment]
While doing Critical Strike for #50 , I found that some used `atk_critical` and others `critical` for attribute. I tested them and they both seem to work identically for melee attacks. So that can be ignored.

**Comment by ak2yny** [comment]
Removing this to get rid of duplicate issues
