### ISSUE TITLE
Luke Cage resistance boost bug

### ISSUE THREAD

**Issue by JordanLeich** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#11]
Author: Cohollow

Date: 20.12.2021

Bug:
Luke Cage's resistance boosting is wrong (costume passive).

**Comment by JordanLeich** [comment]
Here's a screenshot of the +200 percent bug, I'm not sure what the original value should be.

![Cage Bug](https://user-images.githubusercontent.com/57107961/185053130-810eef05-7888-4a80-9876-2d7dd08ecf35.png)

**Comment by ak2yny** [comment]
Compare it with other costume passives. The resistance should be similar. Luke may have a lot of resistance, but the costumes passives must stay in a similar range for the sake of balance

**Comment by JordanLeich** [comment]
> Compare it with other costume passives. The resistance should be similar. Luke may have a lot of resistance, but the costumes passives must stay in a similar range for the sake of balance

I just looked and most characters have a +2 resist to start out with when it comes to the resistance passive. Only main difference I noticed is that Luke Cage may be the only character with a number percentage resistance passive (+200%, while everyone else has +2) so that brings me closer to the conclusion that Luke is meant to have this but still unsure? What are your thoughts.

**Comment by ak2yny** [comment]
Just checking with Deadpool.
His resistance code is the same as Luke's:
```
            "level": {
                "count": 9,
                "description": "+%dead_outfit42_shw All resistances",
                "powerup": {
                    "life": -1,
                    "affecter": {
                        "attribute": "resist_all",
                        "level": "%dead_outfit42_pct"
                    }
                }
```
And this is a boost of 2 - 10 percent (0.02 to 0.1). I don't know why it says +2 for Deadpool, but maybe a resistance of +2 is the same as +2% ?
I'd stick with the description of Deadpool, because it seems to be more correct. (From my understanding it resists 2-10% of all incoming damage.)

**Comment by ak2yny** [comment]
`:p` should go with the actual value, e.g. `+%lukec_outfit33_res:p`.
There is also the `:s` code, which adds a `+`. Don't know, if it also multiplies by 100.

**Comment by ak2yny** [comment]
That's perfect, thank you.
