### ISSUE TITLE
Remove acrobatic challenge code and other talents

### ISSUE THREAD

**Issue by JordanLeich** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#15]
Author: Unknown

TODO: Possibly remove acrobatics from herostat (Ronin) and talents (shared_talents), as there may be no acrobatic challenges in MUA. The code exists in Game.exe though (like other challenges that don't exist in MUA).

**Comment by JordanLeich** [comment]
@ak2yny I removed the acrobatics code from Ronin's talent file and tested in game and she works as normal. I also couldn't find anything about acrobatics or challenges in shared_talents, was there something else that should be removed from shared_talents? Otherwise, I can commit and push the Ronin fix.

**Comment by ak2yny** [comment]
I don't remember any other open issues/changes for shared_talents. Go ahead with this. We can always make more changes later, if something comes up.
