### ISSUE TITLE
Implement the Outsider's fixes from his EXG.

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#20]
- [x] 113 Hand Ninja renumbering from 11305 to 11300 *
- [x] Swordsman boss from Hawkeye's SIM mission, including adding sounds and correcting damage values. *
- [x] Reducing scripts in hub act 2 (strange) and test the Weasel side-quest. [Details](https://discord.com/channels/449510825385000960/449511007811796993/1017284656086925362)
---------------------------
- [x] Add the [Stygian Abyss fix](https://marvelmods.com/forum/index.php/topic,8753.msg203710.html#msg203710) to optional files. (It reduces the enemy variety.)
- [x] Add the [Doom Final Battle fix](https://marvelmods.com/forum/index.php/topic,8753.msg203710.html#msg203710) to optional files. (It reduces the enemy variety.)
- [x] Test the [Magneto saves both X-Men mod](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/tree/master/1%20-%20Optional%20files/Optional%20Save%20Both%20Jean%20and%20Nightcrawler) with and without the Stygian Abyss fix.

(please double-check compatibility with OCP through side-by-side comparison, and also double-check if other files may need to be modified)

\* The Outsider provided details and files on Discord in DM with @ak2yny

**Comment by ak2yny** [comment]
While doing the Stygian Abyss fix, double check Sepulcher > exit to Stygian Abyss:
There is a bug where the Exit would not be marked in some cases, depending on who is saved. This is with the new story arc with Magneto saving both. This bug can probably be ignored. However, apparently something went wrong when this was tested, and now the portal doesn't open at all, when Magneto saves both X-Men.

Thanks to CyborgSun for testing and reporting.

**Comment by ak2yny** [comment]
Here is the fix the Outsider sent for Stygian Abyss:
[Stygian_Abyss_Fix.zip](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/files/9768771/Stygian_Abyss_Fix.zip)
Please check it, as it needs other file edits (such as packages). @ak2yny can provide more details.

**Comment by ak2yny** [comment]
When fixing hub act 2, also check the Weasel side-quest. Currently, we can't give him the answer where to hide, apparently. (Thanks CyborgSun for reporting)

**Comment by ak2yny** [comment]
I just tested the Weasel side-quest, and it seems to work. The latest scripts load from the EXG seems to break the limit (not tested but there have been reports about the Weasel answer not working).

**Comment by ak2yny** [comment]
The Stygian Abyss, and Doom battle fixes should be in optional files, as they reduce the experience slightly. Then, we could also add Spoony's reducers to provide a more crash-free experience.

**Comment by ak2yny** [comment]
Added Swordsman fixes 1e4e85e4013c1cf5e279add6b090c379fe155b50

**Comment by ak2yny** [comment]
The ninjas where fixed before the OCP was even added to GitHub. I just forgot the NPCstat. That's now done as well.

**Comment by JordanLeich** [comment]
@ak2yny I can confirm that the Magneto saves both X-Men mod with and without the Stygian Abyss fix works perfectly. However, I may have found a bug as I'm not sure if this is intentional or not. The Magneto mod turns Jeans model into Silver Surfers model when she is in the cage. Also, when defeating mephisto, the Jean model comes back to normal to kill Mephisto so the cage model is the only issue.
![Game exe Screenshot 2023 01 30 - 17 39 08 65](https://user-images.githubusercontent.com/57107961/215612791-da102c7d-e7f4-45a4-a7fd-bc91ca98f24d.png)

**Comment by ak2yny** [comment]
The bug may be related to the change of JeanSimple to JeanGrey. Is the Silver Surfer the first entry in your herostat?

**Comment by ak2yny** [comment]
I'm currently checking the scripts for hub 2. Already removed the Magneto special greeting: 8da898a58de4d499178eb5ee623468bacdfff1b4
Will probably add that and move optional objectives to main OCP (comparing it to the EXG currently) soon.

**Comment by ak2yny** [comment]
Finally done, and the Weasel conversation works. Scripts are stable at the Sanctum Sanctorum currently.
8dc7c58574018d5b7f587eb7de5c37a70f064218
