### ISSUE TITLE
Omega Elevator (again)

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#21]
The elevator level had a bug with inconsistent enemies appearing, sometimes resulting in a never-ending loop. This was fixed earlier this year, but apparently something went wrong.
The [fix](https://cdn.discordapp.com/attachments/855242726542278687/869249623280209960/weaselBWtrigger_omegaelevator.rar) to compare. (Please double-check it before applying.)

Thanks to CyborgSun for testing and reporting.

**Comment by JordanLeich** [comment]
I tested and couldn't replicate the issue into my game so I'm going to close the issue.

**Comment by ak2yny** [comment]
Just to make it clear for everyone: The fix is implemented, and has been working, except for one time which may have been a false alarm. Again, thank you Cyborg Sun for testing.
