### ISSUE TITLE
Add a Daredevil collectible figure to Attilan's throne room

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#33]
Possibly add a DD figure for consistency.
[Suggested by CyborgSun](https://discord.com/channels/449510825385000960/459176149977792513/1044113320376012871)

**Comment by JordanLeich** [comment]
Currently working on adding this.

**Comment by JordanLeich** [comment]
Completed in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/cc0b0a8105005ae189616605b1ccb65280961846

**Comment by ak2yny** [comment]
I think the collectible makes not sound when picked up (without testing). The sounds seems to belong in the map files. Called `beacon.wav`, hash `ZONE_SHARED/SPECIAL/BEACON`. Sound file should be `town4b_m.zsm`. A sound file which has this sound, would be `giant3_m.zsm`.
Thankfully, it does not seem to have any effects.

**Comment by JordanLeich** [comment]
> I think the collectible makes not sound when picked up (without testing). The sounds seems to belong in the map files. Called `beacon.wav`, hash `ZONE_SHARED/SPECIAL/BEACON`. Sound file should be `town4b_m.zsm`. A sound file which has this sound, would be `giant3_m.zsm`. Thankfully, it does not seem to have any effects.

fixed in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/c673a0e5f34db058a92cf15107c9f635f67af20a
