### ISSUE TITLE
Cyclops huds swapped

### ISSUE THREAD

**Issue by JordanLeich** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#34]
Report: https://discord.com/channels/449510825385000960/449515176312569856/1045827697911275682

Cyclops astonishing and classic huds are swapped by accident.

**Comment by ak2yny** [comment]
Fixed in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/33205d92f14c8ae54fcef4695a877a747abe7954
