### ISSUE TITLE
HUD Issues

### ISSUE THREAD

**Issue by JordanLeich** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#35]
Reports by Rampage

- [x] (Rampage is working on fixing this) Silver Surfer's third skin uses a missing or glitched HUD. (This HUD could just use the same HUD as the first skin probably)
![Surfer](https://user-images.githubusercontent.com/57107961/204160150-1a7c0211-fac3-4fbb-8c03-b18a8e4718c5.png)

- [x] Blade's fourth skin is a bald blade model but his HUD has hair.
![Blade](https://user-images.githubusercontent.com/57107961/204160149-35b4dfc9-9f05-4708-9317-6d3092b34890.png)

**Comment by JordanLeich** [comment]
Surfer hud bug fixed in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/44fc34f55bf8fba276a96d400c898cab0d86a414

**Comment by JordanLeich** [comment]
@ak2yny Regarding the Blade HUD issue, I went ahead and made a custom HUD to match as closely as possible to the in-game model and here's what I made. Do you want this to be used for hud_head_0104.igb in the HUDS folder?

![Blade](https://user-images.githubusercontent.com/57107961/204176188-cceff429-55f2-43aa-9e8e-b11e57ff4af6.png)
![In-game](https://user-images.githubusercontent.com/57107961/204176799-c59f9809-0d4c-457a-8c1e-4e64ebb98726.png)

**Comment by ak2yny** [comment]
I prefer Maegawa's version from the [HUD Fix HUD pack](https://marvelmods.com/forum/index.php/topic,9124.msg176218.html#msg176218)

**Comment by ak2yny** [comment]
![image](https://user-images.githubusercontent.com/92672223/204342965-83b80601-35c8-4a89-8872-2edff145b26a.png)

**Comment by JordanLeich** [comment]
Yes, I like that one much more as well.

**Comment by ak2yny** [comment]
Done https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/17c96989018937981f5f07fb2956e98f7634bf6e
