### ISSUE TITLE
Permanent_Fightstyles.PKGB

### ISSUE THREAD

**Issue by RDH94-EDRAGON94** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#38]
Currently all (3) carryguy fightstyles are added to [packages/generated/maps/package/permanent_fightstyles.pkgb](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/blob/a3ec3cbe1508523badedaf4010713235472a9a2c/packages/generated/maps/package/permanent_fightstyles.pkgb) to fix an issue where their melee sounds wouldn't be loaded after extracting to a different area (as mentioned in the <a href="https://docs.google.com/spreadsheets/d/1q48Yh796rQZKbTQ1jJ7P-gJmcJBLdmOkbfJ5VEP-zjs/edit#gid=896940528">changelog</a>).
It seems like this is tied to a load order where sounds are loaded before the fightstyles are. Adding them to the package gives them priority. Doing so also adds 50+ triggers to load each, which adds to limit issues. I currently know no solution where they'd only be loaded when carryguy characters are on the team.

Epicandragon94 [suggested to combine the carryguy fightstyles into one](https://discord.com/channels/449510825385000960/449511007811796993/1057211758240088124), which is probably the best solution currently.

- [x] [data/fightstyles/fightstyle_colossus_carryguy.xmlb](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/blob/a3ec3cbe1508523badedaf4010713235472a9a2c/data/fightstyles/fightstyle_colossus_carryguy.xmlb)
- [x] [data/fightstyles/fightstyle_hulk_carryguy.xmlb](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/blob/a3ec3cbe1508523badedaf4010713235472a9a2c/data/fightstyles/fightstyle_hulk_carryguy.xmlb)
- [x] [data/fightstyles/fightstyle_juggernaut_carryguy.xmlb](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/blob/a3ec3cbe1508523badedaf4010713235472a9a2c/data/fightstyles/fightstyle_juggernaut_carryguy.xmlb)

- [x] We already created the new [fightstyle_carryguy](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/blob/9ef419ac71fa6bad09876a2f64a26c8c33504ca9/data/fightstyles/fightstyle_carryguy.xmlb), and epicdragon94 created the powerstyles.
- [x] [Packages](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/tree/master/packages/generated/characters) still remain.

- [x] Should probably be tested again as well.

-------------------------------------

Original report:
Currently the permanent_fightstyles.pkgb contains three carry_guy fightstyles (for Colossus, Hulk, and Juggernaut), which inflates trigger count. It might be a good idea to have one fightstyle_carryguy fightstyle. Here is a link to the relevant files for a fightstyle_carryguy (contains a remixed anim file, new powerstyles with appropriate references for Hulk, Colossus, and Juggernaut, a new fightstyle_carryguy file, and an edited package file). Tested and working with Hulk and Colossus but not Juggernaut yet. 
https://www.mediafire.com/file/x64w8au5qjub3jc/Fightstyle+Carryguy.zip/file

**Comment by ak2yny** [comment]
Updated packages 03f2434aa06a74816864a49742fb56c28edf2275

**Comment by ak2yny** [comment]
I just tested this and it works.
Can anyone else do that? Otherwise I'll close this issue.

**Comment by JordanLeich** [comment]
> I just tested this and it seems to work.
> 
> Can anyone else test them? Otherwise I'll close this issue.
> 
> Hulk, Juggernaut, and Colossus use the new carryguy fightstyle.

Tested Hulk, Juggernaut, and Colossus and they all work well. You can close this issue now if you want.

**Comment by ak2yny** [comment]
Thank you.
