### ISSUE TITLE
Lift Sabretooth for the GE stage

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#39]
Small issue.
If Sabretooth is taken from the main OCP files, we should modify [1 - Optional files/Optional Gold Edition Stage/ui/menus/mlm_team_back.igb](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/blob/7dc05ed738f3260c065eb28a97282b3ab51b049f/1%20-%20Optional%20files/Optional%20Gold%20Edition%20Stage/ui/menus/mlm_team_back.igb).
![image](https://user-images.githubusercontent.com/92672223/210420235-b67ef8b1-060c-4806-b8de-ef9dae4588ea.png)

**Comment by JordanLeich** [comment]
fixed in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/6c1f36c529c8858e1d3bbcb17dd2015fd7ce9d40
