### ISSUE TITLE
Add (some of) Spoony's Reducers

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#40]
Since there are plans to add fixes to optional files: #3 #20 
It's probably a good idea to add Spoony's reducers as well. There was a good [comment](https://discord.com/channels/449510825385000960/449511007811796993/1067355495326830652) about it, so I believe not all should be added.

(Need to ask for permission first)

**Comment by JordanLeich** [comment]
Done in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/1d437a033b36906bb62e6b013a3af6fe28e9fb1d
