### ISSUE TITLE
Scripts/conversations not working.

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#42]
https://discord.com/channels/449510825385000960/449511007811796993/1069691679528988792
Assuming they're limit issues.

**Comment by JordanLeich** [comment]
> https://discord.com/channels/449510825385000960/449511007811796993/1069691679528988792 Assuming they're limit issues.

I tested this out and could not replicate any of the issues mentioned, this means its an issue with Cyborg Suns game.
