### ISSUE TITLE
Removal of some optional items conflicting with with EXG (now, or in the future)

### ISSUE THREAD

**Issue by UltraMegaMagnus** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#43]
To remove, or update, but removal preferable in case EXG gets updated. Also to minimize content, because newbies will be confused, and will make life harder with vague reports.
The following can conflict, and can be removed safely without affecting added official content:
- Optional Quick Play Mod 2.0, Maegawa's original Quick Play Mod possibly conflict too with EXG https://marvelmods.com/forum/index.php/topic,9124.msg188408.html#msg188408
- MO2 files to make roster hack working
- Backup OCP 2.3 Toad skins maybe

**Comment by JordanLeich** [comment]
Done in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/5f5fc9a18d43fa81d7f72d168030512212527219
