### ISSUE TITLE
Quest/conversation bug

### ISSUE THREAD

**Issue by JordanLeich** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#48]
Report by Cyborg Sun

- In Act 2, Wong gives you an objective to find the Eye of the Shadow Queen in Mephisto's Realm. However, when you pick it up, the objective automatically completes without you needing to return it (which shouldn't make sense). Talking to Wong after the mission won't play any dialogue relating to you returning it to him either; However, if you portal back during the mission (before completing it) and talk to him, only then will dialogue play where you properly give it to him.

**Comment by ak2yny** [comment]
Could it be, because the parent objective is completed?
Maybe the objective should be changed to a different parent...

**Comment by JordanLeich** [comment]
Fixed in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/77572a486d952a9be5156ef916c0e416fe34ad26
