### ISSUE TITLE
HUD/Skin matching

### ISSUE THREAD

**Issue by ak2yny** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#52]
Following HUDs don't match the skin (thanks metal venger1):

[Current HUDs](https://cdn.discordapp.com/attachments/449511007811796993/1081762222595911831/20230304_205941.jpg)

- [x] Ultimate Iron Man. Should have a dark blue chest but it has two thin white spots. 
- [x] Classic Blade. Should have green glasses (or rather the [skin should have yellow glasses](https://cdn.discordapp.com/attachments/449511007811796993/1081822509659332638/Marvel__Ultimate_Alliance_3_5_2023_1_15_09_AM.png)). We could use [Canino's Classic Blade skin](https://marvelmods.com/forum/index.php/topic,10404.msg201946.html#msg201946), as it has yellow glasses, matching the HUD.
- [x] Street Gear Hawkeye. Should have a black shirt, not white.

**Comment by JordanLeich** [comment]
I'm unsure how to extract HUDs from igb files. I know skinnerUI with Outsiders tutorial shows how to extract Daredevils hud and edit it using Gimp but I can't seem to do this with other HUDs as they contain different offsets with SkinnerUI I believe.

**Comment by ak2yny** [comment]
Yes, they have different offsets. I may have them, or at least I know how to find them. However, Using SkinnerUI results in lower quality (colour issue), so I recommend Alchemy. There are two ways:
- [Texture replacement](https://marvelmods.com/forum/index.php/topic,11009.html) (need to deal with mipmaps)
- [Alchemy batch files](https://marvelmods.com/forum/index.php/topic,10969.msg200476.html#msg200476) (extract first, then use HUD batch)
Let me know if you need more help with it.
