### ISSUE TITLE
Blade spawn with all segments on him after saving him

### ISSUE THREAD

**Issue by UltraMegaMagnus** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#53]
After saving in Fair Ground minigame, he has no segment hidden, only the "0101_sword_back_segment" on his back does not make sense to have, since he is already holding his sword. Or, should has his sword & gun hidden?

The following might be added to blade_button.py (not sure if this is the correct script), but with all known limit, might not be a good idea for a small detail. What do you think?
setSegmentVisible("blade", "0101_sword_back_segment", "0")

![Screenshot 2023-03-27 16-20-29](https://user-images.githubusercontent.com/69069991/227975267-979a21bc-9689-437f-b914-7da76c4354d0.png)
![Screenshot 2023-03-27 16-20-45](https://user-images.githubusercontent.com/69069991/227975275-900e0f5b-544e-4e77-991e-a7fb35312fc3.png)
![Screenshot 2023-03-27 16-21-27](https://user-images.githubusercontent.com/69069991/227975277-10069924-cd3c-4ed3-ad86-4088151982b3.png)

**Comment by JordanLeich** [comment]
After some testing, it looks like the game does not use the blade_button.py

**Comment by JordanLeich** [comment]
@UltraMegaMagnus @ak2yny I cant seem to get his 2 swords and gun to disappear at this part of the game using scripts for some reason and I cant figure out why. Here's the code I'm using in the claw_win.py file:
```
setSegmentVisible("bladesimple", "0101_sword_back_segment", "0")
setSegmentVisible("bladesimple", "0101_sword_segment", "0")
setSegmentVisible("bladesimple", "0101_gun_segment", "0")
setSegmentVisible("blade", "0101_sword_back_segment", "0")
setSegmentVisible("blade", "0101_sword_segment", "0")
setSegmentVisible("blade", "0101_gun_segment", "0")
```
I'm unsure if the model here being uses refers to "blade" or "bladesimple" so I used both cant it didn't work. Any ideas?

**Comment by ak2yny** [comment]
Make sure that Blade is spawned before you hide the segments. I think we should hide the hand segments instead of his sheathed sword.
I'll check the map file for what Blade's name should be.

**Comment by ak2yny** [comment]
Blade's NPC name used is `BladeSimple`. His monster name is `bladeunlock`. The script I'd use is `scripts/act2/murder/murder4/claw_win`.
This line spawns blade:
```py
     act("blade_trapped", "blade_trapped" )
```

**Comment by JordanLeich** [comment]
Blades hand sword & gun now hidden in https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/commit/279eb0df148947ea15877ef2c5ef0eb8a8864440
