### ISSUE TITLE
I have an issue with flying characters not flying

### ISSUE THREAD

**Issue by CeKko45** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#55]
When attempting to fly with flying characters such as iron man or storm, they get stuck in an animation and fall back down to the ground.  I don't know if this is a common issue but it's happend to me.

**Comment by ak2yny** [comment]
I assume it's a limit issue. My characters can fly with the OCP 2.5.

**Comment by CeKko45** [comment]
You were right. I was using Deadpool and Venom on the team which were heavy.  Thank you very much for the support
