### ISSUE TITLE
Bad Mephisto's Realm Warp Point

### ISSUE THREAD

**Issue by CyborgSun** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#56]
Around this area in the first Mephisto map (the place where you need to throw the Leapers into the lava pit), there is a bad teammate warp point where one of them will warp straight into the death abyss.

https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/assets/151224011/36a6d281-51f2-4537-abcb-e167e2a0a00c

**Comment by ak2yny** [comment]
Merged with #9
