### ISSUE TITLE
Leader Invulnerability on Easy-Normal in two spots

### ISSUE THREAD

**Issue by CyborgSun** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#59]
In two specific areas of the game, enemy leaders can have the Invulnerability buffs on Easy-Normal difficulties, which shouldn't be the case, should be an easy enough oversight to correct:

- [ ] One Clay Soldier leader in the Asgard mission (after breaking down the barred door to Heimdall)
- [ ] Some Leaders in the Cityscape map of the Skrull mission (can't remember which ones, could be all of them or just a few specific ones)

**Comment by ak2yny** [comment]
added to #61
