### ISSUE TITLE
Black Panther Sim: Arcade Voice

### ISSUE THREAD

**Issue by CyborgSun** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#60]
In Black Panther's Simulator mission, Arcade does not play any voice clips in the conversation before the boss fight. Are any recorded lines even available in the game?

**Comment by ak2yny** [comment]
The hashes are wrong.

![image](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/assets/92672223/2e6b7693-6291-49ea-9b33-27fd71626c86)

But it's been corrected in the OCP2 (don't remember which version).

![image](https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/assets/92672223/ea97230c-1e9a-42a6-9fd7-532bdbe17805)

**Comment by ak2yny** [comment]
I just realized that the sound file itself hasn't been updated. Will be in the next update. Thanks.

**Comment by ak2yny** [comment]
Fixed 5451d7b3a3016c78f151ce3b193fc73a5bad822e
