### ISSUE TITLE
Ultralizard doesn't drop his unique Lizard's Serum item, but a generic hero-specific one

### ISSUE THREAD

**Issue by Lexonn1** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#63]
This MIGHT be the Enemies mod by Spoony issue, but he doesn't respond to me and looking at the mod it doesn't seem to change Ultralizard's drop.

**Comment by ak2yny** [comment]
Yes, this is because of Spoony's enemies mod. I compared it and in maps/act3/asgard/asgard3.engb, Spoony's mod is missing the `from_enemy` entry for UltraLizard.

If you can, could you test it without that enemies mod and report back if it works?

**Comment by Lexonn1** [comment]
I don't have the vanilla file, buddy.
Would you share it with me please?

**Comment by ak2yny** [comment]
After testing with the correct files, it works again. Thanks for testing, Lexonn1.
