### ISSUE TITLE
Enemies' reflected hits make them bleed

### ISSUE THREAD

**Issue by Lexonn1** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#65]
[+% bleed damage] costume passive ability coupled with [+% reflect melee damage] item passive ability makes enemies receive DOT.
I noticed this after I put **Bulldozer's Helmet** on Wolverine in the blue-yellow suit.
I'm pretty sure only Wolverine's melee attacks are supposed to cause bleeding.

I'm pretty sure other things led to this weird synergy, like radiation harming, but I don't remember exactly.

**Comment by JordanLeich** [comment]
I can confirm this bug exists after testing. In the video, you see me using a skin with no bleed dmg and the bug doesn't work but at the end of the video, I'm using a skin with a bleed dmg boost and the enemy loses health quickly without touching me, which I believe means the enemy getting the reflected dmg is obtaining bleed dmg somehow? https://youtu.be/PYTiEEtwbGQ

**Comment by ak2yny** [comment]
Thanks for the video. I didn't understand the bug initially. I think this can only be changed by using a powerup-tag instead. But I'm not even sure if this is expected or unexpected. I guess since the reflected melee isn't Wolverine's, technically, it shouldn't have bleed damage. Unless, the reflected melee is understood as a counter.

**Comment by Lexonn1** [comment]
@ak2yny Exactly, I honestly think reflect melee is meant to be a counterattack, since characters like Spider-Man have it.
So this interesting combo might be a feature!

**Comment by ak2yny** [comment]
Added to https://github.com/ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance/issues/13
Removing this to get rid of duplicate issues
