### ISSUE TITLE
50-Character Stage camera issues, critical on 4:3 monitors

### ISSUE THREAD

**Issue by techurious** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#67]
With the roster hack enabled, the team stage has a weird camera bug where it resets when you get to the second-to-last column on either side, hiding the last mannequin on either side out of sight.

Before:
![Game exe Screenshot 2024 07 28 - 12 30 32 03](https://github.com/user-attachments/assets/6e01c197-85b3-44f9-bf25-88768f31e97b)
![Game exe Screenshot 2024 07 28 - 12 30 52 64](https://github.com/user-attachments/assets/7adea682-befd-4533-8d83-536edd139329)

After:
![Game exe Screenshot 2024 07 28 - 12 30 40 99](https://github.com/user-attachments/assets/670b8e21-0db1-4061-8bff-b594ff5c7745)
![Game exe Screenshot 2024 07 28 - 12 31 04 47](https://github.com/user-attachments/assets/de1f8f08-85e2-4d38-8714-02eaeb52d735)

What is this caused by and is it possible to fix?

**Comment by ak2yny** [comment]
I think it would be possible. Since the roster hack stage isn't part of the OCP, I'm closing this issue. We can discuss this elsewhere.
