### ISSUE TITLE
Wolverine's Ultimate suit rage duration bonus doesn't affect rage duration/gain at all

### ISSUE THREAD

**Issue by Lexonn1** [ak2yny/Official-Character-Pack-v2-for-Ultimate-Alliance#68]

**Comment by JordanLeich** [comment]
I can confirm this is a bug, currently looking into fixing it.

**Comment by JordanLeich** [comment]
After trying to fix the issue by looking into wolverines talent and powerstyle files, I was unable to fix the bug as I'm not sure why the duration scale isn't applying in game (changing the name references or the time scale didn't change anything in game). Wolverine, along with many other characters, have timed boosts. When upgrading the boosts, the duration timer get longer and longer so maybe that code can somehow be applied to his skin rage duration bonus?

**Comment by Lexonn1** [comment]
I just gave up and replaced that with Melee Mastery passive. xD

**Comment by ak2yny** [comment]
Added to #13 
Removing this to get rid of duplicate issues
